name: 6bwebsite

services:
  mariadb:
    image: mariadb:11
    restart: always
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    user: root
#    command: --init-file=/docker-entrypoint-initdb.d/initfile.sql --max_connections=99999
    expose:
      - 3306
    ports:
      - "0.0.0.0:33123:3306"
    networks:
      - website_net
    environment:
      MARIADB_ROOT_PASSWORD: devenv
    volumes:
      - ${VOLUME_BASE_PATH}/mysql:/var/lib/mysql
#      - ./db-init:/docker-entrypoint-initdb.d:ro
  redis:
    build:
      context: images/redis
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    user: root
#    command: --init-file=/docker-entrypoint-initdb.d/initfile.sql --max_connections=99999
    expose:
      - 6379
    ports:
      - "0.0.0.0:33124:6379"
    networks:
      - website_net
    environment:
      MARIADB_ROOT_PASSWORD: devenv
    volumes:
      - ${VOLUME_BASE_PATH}/redis:/data
  discord-bot:
    build:
      context: ..
      dockerfile: docker/images/discord_bot/Dockerfile
    restart: always
    depends_on:
      - mariadb
      - redis
    networks:
      - website_net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - DISCORD_TOKEN=${DISCORD_TOKEN}

networks:
  website_net: { }
